In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
smart_watch= pd.read_csv('Smart watch prices.csv')
smart_watch


Brand           Model Operating System                Connectivity  \
0       Apple  Watch Series 7          watchOS  Bluetooth, Wi-Fi, Cellular   
1     Samsung  Galaxy Watch 4          Wear OS  Bluetooth, Wi-Fi, Cellular   
2      Garmin          Venu 2        Garmin OS            Bluetooth, Wi-Fi   
3      Fitbit         Versa 3        Fitbit OS            Bluetooth, Wi-Fi   
4      Fossil           Gen 6          Wear OS            Bluetooth, Wi-Fi   
..        ...             ...              ...                         ...   
374  Withings       ScanWatch      Withings OS            Bluetooth, Wi-Fi   
375      Zepp               Z          Zepp OS  Bluetooth, Wi-Fi, Cellular   
376     Honor    Watch GS Pro          Lite OS            Bluetooth, Wi-Fi   
377      Oppo      Watch Free          ColorOS            Bluetooth, Wi-Fi   
378  TicWatch           Pro 3          Wear OS  Bluetooth, Wi-Fi, Cellular   

    Display Type  Display Size (inches) Resolution Water Resistance (meters)  \
0         Retina                   1.90  396 x 484                        50   
1         AMOLED                   1.40  450 x 450                        50   
2         AMOLED                   1.30  416 x 416                        50   
3         AMOLED                   1.58  336 x 336                        50   
4         AMOLED                   1.28  416 x 416                        30   
..           ...                    ...        ...                       ...   
374       PMOLED                   1.38  348 x 442                        50   
375       AMOLED                   1.39  454 x 454                        50   
376       AMOLED                   1.39  454 x 454                        50   
377       AMOLED                   1.64  326 x 326                        50   
378       AMOLED                   1.40  454 x 454                        50   

    Battery Life (days) Heart Rate Monitor  GPS  NFC Price (USD)  
0                    18                Yes  Yes  Yes       $399   
1                    40                Yes  Yes  Yes       $249   
2                    11                Yes  Yes   No       $399   
3                     6                Yes  Yes  Yes       $229   
4                    24                Yes  Yes  Yes       $299   
..                  ...                ...  ...  ...         ...  
374                  30                Yes   No  Yes       $279   
375                  15                Yes  Yes  Yes       $349   
376                  25                Yes  Yes  Yes       $249   
377                  14                Yes   No  Yes       $159   
378                  72                Yes  Yes  Yes       $299   

[379 rows x 13 columns]

In [ ]:
smart_watch['Price (USD)'] = smart_watch['Price (USD)'].str.replace(',', '').str.replace('$', '')

# Convert the Price(USD) column to numeric values
smart_watch['Price (USD)'] = pd.to_numeric(smart_watch['Price (USD)'])
smart_watch.head()

<ipython-input-2-84c8810876a7>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  smart_watch['Price (USD)'] = smart_watch['Price (USD)'].str.replace(',', '').str.replace('$', '')


Brand           Model Operating System                Connectivity  \
0    Apple  Watch Series 7          watchOS  Bluetooth, Wi-Fi, Cellular   
1  Samsung  Galaxy Watch 4          Wear OS  Bluetooth, Wi-Fi, Cellular   
2   Garmin          Venu 2        Garmin OS            Bluetooth, Wi-Fi   
3   Fitbit         Versa 3        Fitbit OS            Bluetooth, Wi-Fi   
4   Fossil           Gen 6          Wear OS            Bluetooth, Wi-Fi   

  Display Type  Display Size (inches) Resolution Water Resistance (meters)  \
0       Retina                   1.90  396 x 484                        50   
1       AMOLED                   1.40  450 x 450                        50   
2       AMOLED                   1.30  416 x 416                        50   
3       AMOLED                   1.58  336 x 336                        50   
4       AMOLED                   1.28  416 x 416                        30   

  Battery Life (days) Heart Rate Monitor  GPS  NFC  Price (USD)  
0                  18                Yes  Yes  Yes        399.0  
1                  40                Yes  Yes  Yes        249.0  
2                  11                Yes  Yes   No        399.0  
3                   6                Yes  Yes  Yes        229.0  
4                  24                Yes  Yes  Yes        299.0

In [ ]:
smart_watch.head()

Brand           Model Operating System                Connectivity  \
0    Apple  Watch Series 7          watchOS  Bluetooth, Wi-Fi, Cellular   
1  Samsung  Galaxy Watch 4          Wear OS  Bluetooth, Wi-Fi, Cellular   
2   Garmin          Venu 2        Garmin OS            Bluetooth, Wi-Fi   
3   Fitbit         Versa 3        Fitbit OS            Bluetooth, Wi-Fi   
4   Fossil           Gen 6          Wear OS            Bluetooth, Wi-Fi   

  Display Type  Display Size (inches) Resolution Water Resistance (meters)  \
0       Retina                   1.90  396 x 484                        50   
1       AMOLED                   1.40  450 x 450                        50   
2       AMOLED                   1.30  416 x 416                        50   
3       AMOLED                   1.58  336 x 336                        50   
4       AMOLED                   1.28  416 x 416                        30   

  Battery Life (days) Heart Rate Monitor  GPS  NFC  Price (USD)  
0                  18                Yes  Yes  Yes        399.0  
1                  40                Yes  Yes  Yes        249.0  
2                  11                Yes  Yes   No        399.0  
3                   6                Yes  Yes  Yes        229.0  
4                  24                Yes  Yes  Yes        299.0

#**Data** **Preprocessing**


In [ ]:
smart_watch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379 entries, 0 to 378
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Brand                      378 non-null    object 
 1   Model                      378 non-null    object 
 2   Operating System           376 non-null    object 
 3   Connectivity               378 non-null    object 
 4   Display Type               377 non-null    object 
 5   Display Size (inches)      376 non-null    float64
 6   Resolution                 375 non-null    object 
 7   Water Resistance (meters)  378 non-null    object 
 8   Battery Life (days)        378 non-null    object 
 9   Heart Rate Monitor         378 non-null    object 
 10  GPS                        378 non-null    object 
 11  NFC                        378 non-null    object 
 12  Price (USD)                378 non-null    float64
dtypes: float64(2), object(11)
memory usage: 38.6+ KB


Check null values

In [ ]:
null_entries = smart_watch.isnull().sum()
null_entries

Brand                        1
Model                        1
Operating System             3
Connectivity                 1
Display Type                 2
Display Size (inches)        3
Resolution                   4
Water Resistance (meters)    1
Battery Life (days)          1
Heart Rate Monitor           1
GPS                          1
NFC                          1
Price (USD)                  1
dtype: int64

Remove null values for operating system

In [ ]:
smart_watch['Operating System'].fillna(method='ffill', inplace=True)

Remove null values for display size in inches

In [ ]:
mean_value = smart_watch['Display Size (inches)'].mean()
smart_watch['Display Size (inches)'].fillna(mean_value, inplace=True)

In [ ]:
null_entries = smart_watch.isnull().sum()
null_entries

Brand                        1
Model                        1
Operating System             0
Connectivity                 1
Display Type                 2
Display Size (inches)        0
Resolution                   4
Water Resistance (meters)    1
Battery Life (days)          1
Heart Rate Monitor           1
GPS                          1
NFC                          1
Price (USD)                  1
dtype: int64

Now we can see there is not any missing value in display size and operating system

# **Training-Testing spillting**

In [ ]:
def split_train_test(data, test_ratio):
     np.random.seed(42)
     shuffle = np.random.permutation(len(data))
     print(shuffle)
     test_set_size = int(len(data) * test_ratio)
     test_indices = shuffle[:test_set_size]
     train_indices = shuffle[test_set_size:]
     return data.iloc[train_indices] , data.iloc[test_indices]

In [ ]:
df=smart_watch
categorical_cols = ['Brand' ,'Model','Operating System'	,'Connectivity' ,'Display Type',
'Display Size (inches)',	'Resolution','Water Resistance (meters)',	'Battery Life (days)',	'Heart Rate Monitor','GPS',	'NFC']

from sklearn.preprocessing import LabelEncoder
# instantiate labelencoder object
le = LabelEncoder()

# apply le on categorical feature columns
smart_watch[categorical_cols] = smart_watch[categorical_cols].apply(lambda col: le.fit_transform(col))
smart_watch

Brand  Model  Operating System  Connectivity  Display Type  \
0        1    127                34             2            17   
1       30     36                31             2             0   
2        8    105                 9             1             0   
3        6    109                 7             1             0   
4        7     43                31             1             0   
..     ...    ...               ...           ...           ...   
374     38     79                32             1            16   
375     41    132                33             2             0   
376      9    119                12             1             0   
377     26    118                 5             1             0   
378     35     71                31             2             0   

     Display Size (inches)  Resolution  Water Resistance (meters)  \
0                       29          27                          5   
1                       18          31                          5   
2                       10          30                          5   
3                       23          19                          5   
4                        9          30                          4   
..                     ...         ...                        ...   
374                     16          21                          5   
375                     17          32                          5   
376                     17          32                          5   
377                     25          17                          5   
378                     18          32                          5   

     Battery Life (days)  Heart Rate Monitor  GPS  NFC  Price (USD)  
0                      8                   0    1    1        399.0  
1                     16                   0    1    1        249.0  
2                      3                   0    1    0        399.0  
3                     22                   0    1    1        229.0  
4                     11                   0    1    1        299.0  
..                   ...                 ...  ...  ...          ...  
374                   14                   0    0    1        279.0  
375                    6                   0    1    1        349.0  
376                   12                   0    1    1        249.0  
377                    5                   0    0    1        159.0  
378                   26                   0    1    1        299.0  

[379 rows x 13 columns]

In [ ]:
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error as MSE
from sklearn.metrics import mean_absolute_error as MAE
from sklearn.metrics import r2_score as r2
from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import MinMaxScaler

In [ ]:
X= smart_watch.iloc[:,0:9].values
Y= smart_watch.iloc[:,9:10].values

In [ ]:
reg = linear_model.LinearRegression()
scale = StandardScaler()
X= scale.fit_transform(X)
Y= scale.fit_transform(Y)


In [ ]:
from sklearn.model_selection import train_test_split
train_set , test_set = train_test_split(smart_watch , test_size = 0.2 , random_state=42)
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=.2,random_state=42)

reg.fit(X_train,Y_train)

print(f"rows in train set: {len(train_set)} \nRows in test set: {len(test_set)}")

rows in train set: 303 
Rows in test set: 76


In [ ]:
smart_watch = train_set.drop("Brand" , axis=1)
smart_watch_labels = train_set["Brand"].copy()

# **Creating Pipeline**

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline = Pipeline([
    ('imputer' , SimpleImputer(strategy="median")),
    ('std_scaler', StandardScaler()),
])

In [ ]:
watch_num_tr = my_pipeline.fit_transform(smart_watch)

In [ ]:
watch_num_tr

array([[ 1.36697091, -0.68857561, -0.34918196, ...,  0.30078082,
         0.41807932, -0.03533468],
       [ 1.4705578 ,  1.15700426,  1.38527926, ...,  0.30078082,
         0.41807932, -0.13520791],
       [-1.71473911,  0.54181097, -0.34918196, ...,  0.30078082,
         0.41807932,  1.31295383],
       ...,
       [ 0.66775939,  0.89334999, -0.34918196, ...,  0.30078082,
         0.41807932, -0.5347008 ],
       [ 0.74544956,  0.89334999, -0.34918196, ...,  0.30078082,
         0.41807932, -0.03533468],
       [-0.78245709,  0.71758048, -0.34918196, ...,  0.30078082,
         0.41807932, -0.5347008 ]])

# **Selecting desired model**

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.cluster import KMeans
#model = LinearRegression()
#model = DecisionTreeRegressor()
model = RandomForestRegressor()
#model = SVR()
#model = KMeans()
model.fit(watch_num_tr,smart_watch_labels)

RandomForestRegressor()

In [ ]:
some_data = smart_watch.iloc[:5]

In [ ]:
some_labels = smart_watch_labels.iloc[:5]

In [ ]:
prepared_data = my_pipeline.transform(some_data)

In [ ]:
model.fit(watch_num_tr,smart_watch_labels)

RandomForestRegressor()

In [ ]:
model.predict(prepared_data)

array([10.  ,  1.7 , 33.06,  8.  ,  8.2 ])

# **Evaluting the model**

In [ ]:
from sklearn.metrics import mean_squared_error
housing_predictions = model.predict(watch_num_tr)
lin_mse = mean_squared_error(smart_watch_labels ,housing_predictions)
lin_rmse = np.sqrt(lin_mse)

In [ ]:
lin_mse

2.830725566831683

In [ ]:
lin_rmse

1.6824760226617446

# **Cross validation -Evalution Technique**

In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model ,watch_num_tr , smart_watch_labels , scoring ="neg_mean_squared_error", cv = 10)
rmse_scores = np.sqrt(-scores)

In [ ]:
rmse_scores

array([6.99138254, 5.82108897, 6.40970585, 3.58214109, 2.41276398,
       5.55159271, 3.68354947, 3.42970261, 3.75665954, 3.382935  ])

In [ ]:
def print_scores(scores) :
  print("Scores :", scores)
  print("mean :" , scores.mean())
  print("Standard deviation :", scores.std())

In [ ]:
print_scores(rmse_scores)

Scores : [6.99138254 5.82108897 6.40970585 3.58214109 2.41276398 5.55159271
 3.68354947 3.42970261 3.75665954 3.382935  ]
mean : 4.502152176379964
Standard deviation : 1.466852985342985


In [ ]:
prepared_data[0]

array([ 1.36697091, -0.68857561, -0.34918196, -0.80884118,  0.50436176,
        1.096341  ,  0.50294954, -0.80594616, -0.05754353,  0.30078082,
        0.41807932, -0.03533468])

In [ ]:
from joblib import dump,load
dump(model , 'smart_watch.joblib')

['smart_watch.joblib']

In [ ]:
from joblib import dump,load
model = load( 'smart_watch.joblib')

In [ ]:
features = np.array([[ 1.36697091, -0.68857561, -0.34918196, -0.80884118,  0.50436176,
        1.096341  ,  0.50294954, -0.80594616, -0.05754353,  0.30078082,
        0.41807932, -0.03533468]])
model.predict(features)

array([10.])